#include <stdio.h>

// Array of string pointers
const char *textBefore[] = {
    "Delete time off; Redondo Beach; Fri, May 9, 2025, 5:00 PM UTC; Fri, May 9, 2025, 7:00 PM UTC; Thu, May 8, 2025, 1:10 AM",
    "HQ; Feb 1, 2026",
    "HQ",
    "HQ — Redondo Beach, CA, USA",
    "HQ; Josh Peacock sent a reply via email from HQ",
    "HQ",
    "HQ",
    "HQ; Team owner: HQ / Redondo Beach, CA, USA; Access row: HQ / Redondo Beach, CA, USA",
    "zaya@endearhq.com; Click to set available hours; Zaya Amgaabaatar; HQ (owner)",
    "HQ; mark lopez / Duncan Regan / Darrell Ciatti (customer rows, various emails/dates)",
    "HQ; mark lopez / Duncan Regan / Darrell Ciatti (customer rows, various emails/dates)",
    "HQ; HQ / Redondo Beach; none; Include calendars owned by the all members of HQ",
    "HQ; HQ / Redondo Beach; none; Include calendars owned by the all members of HQ",
    "HQ",
    "HQ; H (orange badge, Owner column, HQ rows)",
    "HQ; H (orange badge, Owner column, HQ rows)",
    "Table starts with mark lopez (no Ross Geller row); HQ; Endear Team / none / (blank email, blank date)",
    "Table starts with mark lopez (no Ross Geller row); HQ; Endear Team / none / (blank email, blank date)",
    "HQ; none; Recent Messages",
    "HQ; none; Recent Messages",
    "HQ; none",
    "HQ; none",
    "HQ",
    "HQ",
    "HQ",
    "HQ",
    "HQ; Showing 5 of 5 conversations; none; Phoebe Buffay / Hello there! - Hi Phoebe, I wanted to let you know we're having a sample sale this weekend from 11am - 2pm. We'll have free coffee and a s...",
    "HQ",
    "HQ; none; Endear Team / (no email) / Apr 25, 9:42 PM; Glen Vannoni, Tyler Scarselli, Jorge Talbot, Jackson Giannoni, Darrell Ciatti (customer rows)",
    "HQ; none; Endear Team / (no email) / Apr 25, 9:42 PM; Glen Vannoni, Tyler Scarselli, Jorge Talbot, Jackson Giannoni, Darrell Ciatti (customer rows)",
    "Team is HQ",
    "HQ",
    "HQ",
    "HQ",
    "HQ",
    "HQ; Phoebe Buffay",
    "HQ; Phoebe Buffay",
    "Team is HQ",
    "Team is HQ",
    "HQ; mark lopez / Duncan Regan / ben@endearhq.com / Josh Greene / Chandler Bing (customer rows), darrell.ciatti@sink.sendgrid.net / roger.gianassi@sink.sendgrid.net (email rotation); Phoebe Buffay",
    "HQ; mark lopez / Duncan Regan / ben@endearhq.com / Josh Greene / Chandler Bing (customer rows), darrell.ciatti@sink.sendgrid.net / roger.gianassi@sink.sendgrid.net (email rotation); Phoebe Buffay",
    "HQ",
    "HQ",
    "HQ",
    "HQ",
    "HQ / Redondo Beach, CA, USA; Active",
    "HQ / Redondo Beach, CA, USA; Active",
    "HQ; Phoebe Buffay; 12h ago",
    "HQ; none",
    "HQ / Redondo Beach, CA, USA",
    "H",
    "HQ; Showing 8 of 8 conversations; Hello there! / Re: New ties in stock! / Happy Birthday from Suburban Outfitters! (Phoebe Buffay, Chandler Bing, Annie Graham rows)",
    "0; HQ",
    "HQ; Redondo Beach, CA, USA",
    "HQ",
    "HQ",
    "HQ; none",
    "Phoebe Buffay; Hi Phoebe,",
    "HQ",
    "HQ (selected) / Redondo Beach; Active",
    "HQ",
    "Manhattan Beach, Home, Customers, Appointments, Campaigns, SalesChat, Inbox (Try new inbox), Creative>Stories, Products, Assets, Insights, Data (expanded text nav); Search everything... (visible search bar)",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Try new inbox, Creative, Insights, Data (sidebar labels); Ribbed Bodycon Midi Dress (name field, dress photo unchanged); none; none",
    "no change",
    "Created by me (13)",
    "Pin to top",
    "HQ",
    "HQ",
    "HQ",
    "HQ",
    "HQ",
    "AI Opportunity Engine / Help your team send more personalized messages in less time. AI identifies high-intent customers and drafts messages for associate review. / Configure for your brand; Away; none",
    "Josh Peacock @joshpeacock, Away toggle; AI Opportunity Engine — Help your team send more personalized messages in less time. Configure for your brand; none; none",
    "AI Opportunity Engine / Help your team send more personalized messages in less time. AI identifies high-intent customers and drafts messages for associate review. / Configure for your brand; Away; none",
    "Off; none; none; Example Brand, HQ, Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data (expanded labeled sidebar)",
    "Working hours Off; none; none; Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Try new inbox, Creative, Insights, Data, Switch accounts, Settings, What's new, Setup guide (sidebar labels)",
    "Off; none; none; Example Brand, HQ, Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data (expanded labeled sidebar)",
    "none",
    "no change",
    "Thu, Feb 12, 2026",
    "Pheebs Buffay",
    "Home, Customers, Audiences, Notes, Tasks, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data, Switch accounts, Settings, What's new, Setup guide, Help center, Chat with support, Josh Peacock @joshpeacock",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data, Switch accounts, Settings (labeled nav); Edit email signature, Compose, Search everything...",
    "no change",
    "Pheebs Buffay",
    "Manhattan Beach, Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Try new inbox, Creative, Insights, Data, Switch accounts, Settings, What's new, Setup guide, Help center, Chat with support, Josh Peacock",
    "none",
    "John Jackson, Chandler Bing, Monica Geller, Rachel Green (~20+ staff rows with many duplicates); Import CSV / + Add staff members",
    "no change",
    "no change",
    "no change",
    "none; none",
    "Try new inbox",
    "Try new inbox",
    "Try new inbox",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "none; Notifications, Billing, Brand, Security, Staff, Teams, Customers, Contact methods",
    "none; none",
    "none; Notifications, Billing, Brand, Security, Staff, Teams, Customers, Contact methods",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "Language / Select the default language for your account / English; none; none",
    "no change",
    "no change",
    "Any tasks assigned to you will appear here",
    "Any tasks assigned to you will appear here",
    "Away",
    "Away",
    "Manhattan Beach org switcher, Home/Customers/Appointments/Campaigns/SalesChat/Inbox/Creative/Insights/Data, footer Switch accounts/Settings/What's new/Setup guide/Help center/Chat with support, Josh Peacock user card (expanded text nav); Search everything... (visible search bar)",
    "no change",
    "no change",
    "Example Brand / Manhattan Beach / Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data / Josh Peacock (expanded labeled sidebar); none",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data, Settings (labeled nav); none; Search everything...; Pheebs Buffay",
    "Event Styling / Let's style you for a specific event! Whether it's something formal like a wedding or graduation, or something casual - we'd love to help you feel your best!; Pheebs Buffay; Edit; https://examplebrand.endear.events/services?event-type=apt_type_01k9zrxdf2esh...",
    "Noto Sans JP",
    "Pheebs Buffay; Try new inbox",
    "no change",
    "none",
    "Event Styling; Let's style you for a specific event! Whether it's something formal like a wedding or graduation, or something casual - we'd love to help you feel your best!; Edit; https://examplebrand.endear.events/services?event-type=apt_type_01k9zrxdf2esh...",
    "no change",
    "no change",
    "none",
    "Pheebs Buffay",
    "no change",
    "no change",
    "no change",
    "no change",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Try new inbox, Creative, Insights, Data, Switch accounts, Settings, What's new, Setup guide, Help center, Chat with support (sidebar labels)",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data (labeled nav) / Manhattan Beach org banner; Search everything... (input); Oversized Graphic Sweatshirt, Band Tee, Ribbed Bodycon Midi Dress (image grid order)",
    "Home, Customers, Audiences, Notes, Tasks, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data, Switch accounts, Settings, What's new, Setup guide, Help center, Chat with support, Josh Peacock @joshpeacock; none",
    "no change",
    "no change",
    "Any tasks assigned to you will appear here",
    "Title, Status, Type, Start date, End date, Schedule, Tags, Creator",
    "no change",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative (Stories, Products, Assets), Insights, Data (labeled nav items); Manhattan Beach (org/store switcher label); Search everything...",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data (nav text labels); Search everything...",
    "Manhattan Beach, Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data, Switch accounts, Settings (labeled nav); Notifications, Billing, Brand, Security, Staff, Teams, Customers, Contact methods; none; none",
    "no change",
    "8mo ago / 5mo ago / 2mo ago",
    "no change",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Stories, Products, Assets, Insights, Data, Manhattan Beach (expanded sidebar labels)",
    "Manhattan Beach, Home, Customers, Audiences...; none",
    "no change",
    "none; none; Schedule, Send email",
    "Home, Customers, Audiences, Notes, Tasks, Appointments, Campaigns, SalesChat, Inbox (expanded light sidebar with text labels); real timestamps (Last activity); none",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox, Creative, Insights, Data (labeled nav); none; none; 8mo ago / 7mo ago",
    "Schedule",
    "no change",
    "account header, labeled nav items (Home, Customers, Appointments, etc.), Switch accounts/Settings/help links, profile card",
    "no change",
    "no change",
    "8mo ago; 7mo ago — opened; none",
    "Add task / Add customer / Search everything...; none; Chandler Bing, Amy Green",
    "Manhattan Beach",
    "no change",
    "Home, Customers, Appointments, Campaigns, SalesChat, Inbox (Try new inbox), Creative, Insights, Data, Switch accounts, Settings, What's new, Setup guide, Help center, Chat with support, Josh Peacock @joshpeacock (labeled sidebar items)",
    "R Redondo Beach / M Manhattan Beach (owner avatar + location text, 5 rows)",
    "no change",
    "no change",
    "no change",
    "no change",
    "Jasmine Tudor/@jasminetudor, Jinesh Shah/@jinesh (Creator checklist)",
    "Birthday: None; Address: None",
    "Page Views 0",
    "Page Views 0",
    "Showing 7 of 7 stories; none",
    "no change",
    "no change",
    "no change",
    "Time off; 20 appointments; none; Jun 13, 2025 3:00 AM UTC / May 9, 2025 5:00 PM UTC / May 16, 2025 5:00 PM UTC (row dates, pagination footer)",
    "no change",
    "no change",
    "no change",
    "Joey Tribbiani / Dr. Geller / Brad Kane / Duncan Rogan / Lisa Tristan (customer list rows, with matching emails, phones, dates)",
    "Fri, Apr 10, 2026, 10:00 AM - 12:00 PM UTC; Fri, Apr 17, 2026 ... May 8, 2026 (remaining rows); none",
    "no change",
    "no change",
    "none",
    "Feb 5, 2026 — Appointment booked 11:53 PM; When Fri, Feb 6, 2026, 6:00 PM / Duration 60 minutes / Location Redondo Beach, Redondo Beach, CA, USA / Title Custom Tailoring",
    "no change",
    "My new task; Josh Peacock (active toggle profile card); none; Your upcoming appointments will appear here; Your created or scheduled drafts will appear here",
    "1 total issues must be resolved before scheduling; none",
    "0",
    "Apr 4, 2026",
    "no change",
    "Showing 14 of 14 templates; none",
    "(empty)",
    "(empty)",
    "no change",
    "no change",
    "no change",
    "no change",
    "none; Pant size / Numerical pant size; Preferred Fabrics / None, Loyalty Status / None, Color Palette / no description",
    "Birthday: None, Address: None (Phoebe Buffay row)",
    "Birthday: None, Address: None (Phoebe Buffay row)",
    "no change",
    "no change",
    "Showing 7 of 7 stories; My Story",
    "Showing 7 of 7 stories; My Story",
    "no change",
    "no change",
    "Showing 6 of 6 stories; Copy of My Story; none",
    "Showing 6 of 6 stories; Copy of My Story; none",
    "Page Views 0",
    "Page Views 0",
    "Page Views 0",
    "Page Views 0",
    "no change",
    "no change",
    "no change",
    "no change",
    "Showing 6 of 6 stories; Copy of My Story (2 Pieces); Summer Faves (6 Pieces); none",
    "Showing 6 of 6 stories; Copy of My Story (2 Pieces); Summer Faves (6 Pieces); none",
    "no change",
    "no change",
    "The 13th, 17th, 19th, 22nd of May; Apr 14th from 10am - 12pm",
    "The 13th, 17th, 19th, 22nd of May; Apr 14th from 10am - 12pm",
    "2 selected; none",
    "2 selected; none",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "42 appointments; none; None (Assigned to column, most rows)",
    "no change",
    "Josh Peacock @joshpeacock; Managers & admins; Liza Lopez @lizalopez",
    "Showing 6 of 6 conversations; none; none",
    "no change",
    "Today's opportunities / No opportunities available right now.; none; This Week / Messages sent 0 / Attributed sales $0; Upcoming appointments (empty placeholder); My new task, My new task (Pending tasks); Recent drafts (empty placeholder)",
    "Today's opportunities / No opportunities available right now.; none; none; Your upcoming appointments will appear here; Your created or scheduled drafts will appear here",
    "no change",
    "no change",
    "Phoebe Buffay: Birthday None; Phoebe Buffay: Address None",
    "no change",
    "Selected 44 contacts; Ana / rixmose@icloud.com / emprendeser@gmail.com (top rows); Aug 19, 2025",
    "no change",
    "no change",
    "no change",
    "ANOTHER MONTHLY BILL FOR / Video Hosting / $432/mo",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "Blog; hc1.mykajabi.com/blog; Views All Time: 1,103; Theme: Carl; Created: Jul 1 2021 7:41PM, Updated: Sep 22 2025 6:11PM; chart dates 2026-03-29 to 2026-04-05",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "none",
    "no change",
    "no change",
    "You've built out 19 products and have payment set up, but there's...",
    "You've built out 19 products and have payment set up, but there's",
    "You've built out 19 products and have payment set up, but there's...",
    "no change",
    "You've built out 19 products and have payment set up, but there's...",
    "You've built out 19 products and have payment set up, but there's...",
    "You've built out 19 products and have payment set up, but there's...",
    "You've built out 19 products and have payment set up, but there's...",
    "theodore.mykajabi.com/affiliate_users/sign_up; none; Sign up; none; Require PayPal email address at sign-up: unchecked; none",
    "no change",
    "no change",
    "You've built out 19 products and have payment set up, but there's...; none",
    "You've built out 19 products and have payment set up, but there's...",
    "You've built out 19 products and have payment set up, but there's...",
    "no change",
    "no change",
    "no change",
    "no change",
    "none; You've built out 19 products and have payment set up, but there's",
    "You've built out 19 products and have payment set up, but there's...; none",
    "none; You've built out 19 products and have payment set up, but there's",
    "You've built out 19 products and have payment set up, but there's; none",
    "no change",
    "none; You've built out 19 products and have payment set up, but there's",
    "You've built out 19 products and have payment set up, but there's; none",
    "none; You've built out 19 products and have payment set up, but there's...",
    "none; You've built out 19 products and have payment set up, but there's; 7 (selected calendar day)",
    "none; You've built out 19 products and have payment set up, but there's",
    "You've built out 19 products and have payment set up, but there's",
    "You've built out 19 products and have payment set up, but there's",
    "You've built out 19 products and have payment set up, but there's; none",
    "no change",
    "no change",
    "no change",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "More",
    "none",
    "none",
    "none",
    "none",
    "More",
    "no change",
    "none",
    "none",
    "none",
    "Mastering the Basics: Essential Cooking Techniques with Chef Carl; Hello there, food enthusiasts! Welcome to this week's newsletter. We're thrilled to have Chef Carl with us, sharing his expertise on mastering the basics of cooking. So, buckle up and get ready to turn your kitchen into a culinary playground!; The Art of Sauteing; Sauteing is a fundamental cooking technique that involves cooking food quickly in a small amount of oil or fat. It's perfect for vegetables, meat, and seafood. Chef Carl recommends using a wide, heavy-bottomed pan and keeping the heat medium-high. What's your go-to dish to saute? Share your saute experiences or any questions you might have!",
    "no change",
    "none; none; none; none",
    "2025 Goals Challenge: Please Confirm Your Subscription; You're almost in... Please click the button below to confirm your subscription to the Kickstart 2025 with Clarity and Confidence Challenge! (plus additional body copy); Confirm subscription; 2025 Challenge Thank You",
    "none; Complete Digital Marketing Mastery for Small Business Owners: From Zero to $10K Monthly Revenue Waitlist (When/Then/If automation rule)",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "no change",
    "none; none",
    "More",
    "none",
    "none",
    "none",
    "no change",
    "no change",
    "none",
    "none",
    "no change",
    "no change",
    "no change",
    "none",
    "none",
    "no change",
    "none",
    "You've built out products, offers, and a presale page, but there's; Active Users 27; Last updated: May 04 2026, 01:19 PM UTC; none; Messages sent 8 more; Apr 4",
    "no change",
    "no change",
    "Lennard Shelbi / lennard@gmail.com (name-card panel); none; 1:1 Wellness Coaching Program / Sessions 1-6, August 15, 2022 dates; none",
    "none; You've already built products, offers, and a presale page, but",
    "none; You've already built products, offers, and a presale page, but",
    "You've already built products, offers, and a presale page, but",
    "Passed text / You passed this assessment.; Failed text / You failed this assessment.",
    "no change",
    "Kajabi Help Center; none; none",
    "none; none",
    "Kajabi Help Center; none; Displaying 1-25 of 48 contacts; susanna / Andrea / L Reiff / kamille aerron / Ana / delphine rault / Kenneth Rix (mostly Subscribed)",
    "Third Party Integrations; none; none; Kajabi Help Center",
    "Apr 23 - Apr 30 / May 1 - May 8",
    "How to Embed a Podcast / How To Market A Blog / How to Create A Blog / How to Categorize Your Blog Posts (Kajabi Help Center demo posts); Showing 1-4 of 4 results; Kajabi Help Center; none; none",
    "none",
    "none",
    "Summary $0.50 Sales / 1 Offers Sold / 1 First Purchases; Carl's Intro To Baking, Single, $0.50, 1, 1 (offers row); none",
    "OFFERS SOLD 1; Summary $0.50 / 1 offer sold / 1 first purchase; Offers filter: Choose up to 5 Offers dropdown",
    "no change",
    "Blog Search (Updated April 29, 2025), Announcements (Updated April 25, 2025), Thank You (Updated April 18, 2025), Newsletter Subscribe/Post/Newsletter/Member Directory (Updated April 18, 2025), Kajabi Help Center; none",
    "no change",
    "none; none; Kajabi Help Center",
    "Keeping Up With Carl; \"Keeping Up With Carl\" is a weekly cooking newsletter that brings fresh, eas...; Kajabi Help Center; none",
    "Carl's Intro To Baking",
    "none; none; Kajabi Help Center; Analytics > Reports; none",
    "Carl's Exclusive Ebook / Discover \"Chef Carl's Ultimate Cookbook\"... / 33 members / 1 Download; Kojabi Help Center",
    "Displaying 4 Funnels: Freebie, Upcoming Company Webinar, Product Launch Funnel, Sales Funnel; none; Kajabi Help Center",
    "Displaying 21 Website Pages; Blog / Store / Blog Post / Home (System badge); Kajabi Help Center; none",
    "none",
    "Kajabi Help Center; none; none; 1 - 25 of 89 Events; Alex Mcdowl / john smith (1:1 Wellness Coaching Program rows)",
    "no change",
    "none; none; Freebie Form / Gold Membership Waitlist / Silver Membership Waitlist (forms rows); Push Notifications (Marketing nav item); Universal Inbox Beta badge",
    "Kajabi Help Center; Someone's In the Kitchen!; This community will exist to foster the love we all have for cooking while sharing our experiences along the way!; none",
    "Kajabi Help Center / Someone's In the Kitchen!; This community will exist to foster the love we all have for cooking while sharing our experiences along the way!; Additional payment options: PayPal (visible)",
    "no change",
    "Share a Blog Post, Share a Newsletter, Simple Text, Showcase a Product, Announce an Event, Share Knowledge (wireframe template cards); none",
    "none; Kajabi Help Center; none; Johnny O'Connor / helpcenter@kajabi.com / Subscribed / $1.50 / Oct 6, 2021 / May 21, 2025 (contact row); Keeping Up Wit... (filter chip value)",
    "no change",
    "no change",
    "no change",
    "no change",
    "Landing page selector: Automation Masterclass Presale Landin...; Complete Digital Marketing Mastery for Small Business Owners: From Zero to $10K Monthly Revenue Waitlist; none",
    "no change",
    "no change",
    "no change",
    "no change",
    "none",
    "no change",
    "none; none",
    "none",
    "About / Updated: March 02, 2026 07:52 PM; none; none",
    "no change",
    "no change",
    "Nutrition (Updated May 07, 2026 05:25 PM), Freebie Funnel Email Sequence, Total Body Strength Program - Post Purchase Thank You, Get your Nutrition Guide - No Cost to You!, The Ultimate Nutrition Guide - For Free!, You don't need to be strong to start, 30-Day Transformation Challenge - Cohort 1 Course Ready Broadcast, Total Body Strength Program Course Ready Broadcast (campaign rows, statuses Draf",
    "none",
    "none; none; none; none",
    "About (first, Updated March 02, 2026)",
    "Updated 5 days ago; none; none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "no change",
    "no change",
    "no change",
    "none; none; You've already built the 30-Day Transformation Challenge offer",
    "none; You've already built the 30-Day Transformation Challenge offer",
    "none",
    "You've already built the 30-Day Transformation Challenge offer",
    "Offers (0)",
    "You've already built the 30-Day Transformation Challenge offer; Clients (0); Offers (0); none; none",
    "You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer",
    "none; Enrolled clients 0; 1 Events; none; You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer",
    "none; You've already built a full 30-Day Transformation Challenge funnel",
    "You've already built a full 30-Day Transformation Challenge offer (tooltip); none",
    "Experience the upgraded builder - cleaner UI, smarter organization, and powerful new updates coming soon. Explore and upgrade; You've already built a full 30-Day Transformation Challenge funnel! (tooltip)",
    "none; You've already built a full 30-Day Transformation Challenge funnel",
    "none; You've already built a full 30-Day Transformation Challenge funnel (coach-mark tooltip)",
    "none; You've already built a full 30-Day Transformation Challenge funnel",
    "none; You've already built a full 30-Day Transformation Challenge funnel",
    "none; You've already built a full 30-Day Transformation Challenge funnel (coach-mark tooltip)",
    "none; You've already built a full 30-Day Transformation Challenge funnel",
    "Corey Piazza (LB) Export of Recent Incoming Messages — Sent on: August 14, 2025 1:24 PM; Message details Sent: August 14, 2025 1:24 PM",
    "none",
    "Filters: All, Email, SMS, Video, Voice Broadcast, Reminder; (913) 302-6686 / SMS Created 2025-07-11 / Sent on: July 11, 2025 9:45 PM",
    "Corey Piazza (LB) Export of Recent Incoming Messages — Sent on: August 14, 2025 1:24 PM",
    "3048074477 / 3048074478; Connect Cards (6)",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "Status: All systems are go! Updated 04 Jan 00:02 - Click for details; Crafting the perfect text message / Your Quick Start Set-Up / Frequently Asked Questions / Allotment and Usage FAQs",
    "no change",
    "no change",
    "no change",
    "none",
    "no change",
    "no change",
    "no change",
    "no change",
    "none",
    "no change",
    "no change",
    "no change",
    "no change",
    "none; none",
    "(913) 30..., (816) 45... (2 phone contacts above Daniel Murphy)",
    "no change",
    "no change",
    "none",
    "no change",
    "People Created 0, Out of 22 total; Emails Sent 1; People donut 23, 2 Incoming Message",
    "133 days ago",
    "no change",
    "no change",
    "none",
    "no change",
    "no change",
    "no change",
    "none; none; Send \"New mercies\" / Send \"Checking in\" / Send \"Prayer check in\" (top steps, no first step present)",
    "none",
    "no change",
    "Groups | People",
    "no change",
    "no change",
    "none",
    "no change",
    "4 People Created (Out of 26 total); 9 Calling (2 Completed, 15 Incoming Call); 27 People (5 Incoming Call); 1.57 Minutes Used",
    "2 Completed; 15 Incoming Call",
    "1.57 Minutes Used, 4 People Created (Out of 26 total); 9 calls, 2 Completed; 27 People, 15 Incoming Call",
    "4 People Created; Out of 26 total; 9 Calling (5 Incoming Call, 2 Voicemails, 2 Completed); 27 People; 1.57 Minutes Used",
    "People Created 4 (Out of 26 total); Calling 9; People 27; Minutes Used 1.57",
    "By submitting, you agree to receive communications from us. Text STOP to cancel or HELP for assistance.",
    "4 People Created, Out of 26 total; 1.57 Minutes Used; Calling: 9 total, 2 Completed; People: 27 total",
    "no change",
    "no change",
    "no change",
    "0.60 Minutes Used; People Created 3 of 26 total; Calling 6 (2 Completed, 0 Outgoing, 2 Voicemails, 2 Missed); People 27 (15 Incoming Call)",
    "By submitting, you agree to receive communications from us. Text STOP to cancel or HELP for assistance.; none",
    "none",
    "no change",
    "no change",
    "no change",
    "You have no remaining numbers. Purchase additional numbers for $4/mo.; (816) 731-1363",
    "You have no remaining numbers. Purchase additional numbers for $4/mo.; 58 Receptionist",
    "09-23-2025 / 12-23-2025 / 1-23-2026 (invoice date rows, top row)",
    "From: Emily - emily@test.com",
    "26 Total People; 2 recently added; 24 Opted in / SMS Communication; 26 Opted in / Email Communication",
    "Connect Cards (2)",
    "26 Total People; 24 Opted in (SMS); 26 Opted in (Email); 2 recently added",
    "{STAFF_NAME}; {STAFF_NAME2}; {STAFF_NAME3}",
    "Visible invoice dates: 09-23-2025 through 04-23-2025 (7 rows)",
    "...press 2. To share a prayer request with our prayer team, press 3. If you want to learn about service opportunities, please press 4. For our staff directory, press 5. And, if you'd like to visit our website, go to https://textinchurch.com, or press 6, and we'll text you a link to access it. Press star to repeat the menu options. Thanks for calling, and have a blessed day.; SMS text message content area not visible",
    "2 Phone Number",
    "Hi {First Name}[purple pill] - it's {PASTOR_FNAME}[purple pill] here...we hope to see you tomorrow @ {CHURCH_NAME}[purple pill]!",
    "none (empty compose area, 0/160 characters)",
    "26 Total People; 24 SMS Opted In; 26 Email Opted In; 2 recently added",
    "26 (Total People); 2 recently added",
    "26 (Total People); 24 (Opted in, SMS Communication); 26 (Opted in, Email Communication); 2 recently added",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "26 Total People; 2 Opted out (SMS); 26 Opted in (Email)",
    "26 Total People; 24 Opted in / 2 Opted out SMS; 26 / 0 Email",
    "no change",
    "Blocked (filter option inside Filters dropdown); Total People 22, SMS opted in/out 20/2, Email opted in/out 22/0",
    "Out of 27 total; 1.82 Minutes Used; 10 calls, 3 Completed, 3 Outgoing",
    "3 Completed, 3 Outgoing, 2 Voicemails, 2 Missed",
    "1.82 Minutes Used; 10 (Calling total); Out of 27 total (People Created); 3 Completed, 3 Outgoing",
    "none; 1 Open",
    "Out of 27 total (People Created); 1.82 Minutes Used; 10 calls (Calling donut total); 3 Completed, 3 Outgoing",
    "1.82 Minutes Used; 10 calls; Out of 27 total; 3 Completed; 3 Outgoing",
    "1.82 Minutes Used; Calling 10 (Completed 3, Outgoing 3); Out of 27 total",
    "Keyword; Leadership (sample) Members: 1",
    "Connect Cards (84)",
    "no change",
    "no change",
    "(816) 731-1362 / Completed; (314) 701-6954 / Vmail Answer",
    "[icon-only button, unlabeled]; [icon-only button, unlabeled]",
    "(816) 731-1362 Completed, (314) 701-6954 Vmail Answer, (816) 731-1363 Completed (Call History rows); 80 Receptionist",
    "no change",
    "09-23-2025 / 12-23-2025 / 01-23-2026 (invoice date rows)",
    "none (icon only); none (icon only)",
    "no change",
    "25 Opted in, 2 Opted out (For SMS Communication)",
    "Connect Cards (84)",
    "Assign Users (Optional) - Select from the dropdown...",
    "158 Receptionist, 1 Active / Church Digital Receptionist (Inactive) x3, This is your churches main digital receptionist; (816) 731-1362 Completed (phone-number call history rows)",
    "none (icon-only buttons); none (icon-only buttons)",
    "Keyword",
    "Opted In: 25, Opted Out: 2",
    "Keyword; Leadership (sample): 1 member, 4 workflows",
    "Keyword; Leadership (sample) Members: 1",
    "Connect Cards (84)",
    "no change",
    "Assign Users (Optional) / Select from the dropdown...",
    "Keyword (column header); Leadership (sample): 1 member",
    "none; none; none",
    "Start time: 06:00 PM; End time: 06:00 PM",
    "none; none; none",
    "09-23-2025 / 10-23-2025 / 11-23-2025 (invoice dates)",
    "All Settings, Sender Profile, Refer a Friend, Billing (Payment, Subscriptions, Invoices), System (flat list); none; none; none",
    "none",
    "Easter Igniter Kit / Your Easter communication done for you!",
    "none; none",
    "none",
    "no change",
    "none",
    "no change",
    "no change",
    "25 Opted in, 2 Opted out (For SMS Communication)",
    "25 Opted in, 2 Opted out (For SMS Communication)",
    "no change",
    "https://into.church/fMuJo4vw (row 1), https://into.church/SeE90vRI (row 2)",
    "Keyword; First time guest / Leadership (sample) Members: 0 / 1",
    "no change",
    "(816) 731-1362 Completed / (314) 701-6954 Vmail Answer x2 (call history rows)",
    "https://into.church/fMuJo4vw (row 1), https://into.church/SeE90vRI (row 2)",
    "Connect Cards (84)",
    "Keyword; Leadership (sample) Members: 1",
    "25 Opted in, 2 Opted out (For SMS Communication)",
    "Connect Cards (84)",
    "Keyword; 1 (Leadership (sample) row, Members column)",
    "25 Opted in, 2 Opted out (For SMS Communication)",
    "Connect Cards (84)",
    "(816) 731-1362 Completed, (314) 701-6954 Vmail Answer x2",
    "no change",
    "(816) 731-1362 Completed; (314) 701-6954 Vmail Answer; (314) 701-6954 Vmail Answer",
    "25 Opted in, 2 Opted out (For SMS Communication)",
    "Corey Piazza (LB) Aug 14, (913) 302-6686 Jul 11, (816) 457-3252 Jun 12, (816) 589-0834 Apr 8, + 1 more (list rows)",
    "27 Total People; 0 recently added; 24 Opted in SMS; 27 Opted in Email",
    "Top rows: wuNzTmZ0, 1WvFa0AE, fMuJo4vw, SeE90vRI, INAJA5SI, FODCqka7 (destination-URL codes)",
    "Google Test / Completed / (863) 209-4010 (x2), (816) 731-1363 / Completed",
    "People Created Out of 27 total; 16 In (Calling badge)",
    "248 days ago; none",
    "Google Test, Completed, (863) 209-4010 (row 1); Google Test, Completed, (863) 209-4010 (row 2); (816) 731-1363, Completed (row 3)",
    "28 (People donut center); Out of 27 total (People Created); 16 Incoming Call",
    "Local Number / (816) 477-1966 (Missed tab top rows: (816) 731-1362 Completed, (314) 701-6954 Vmail Answer x2)",
    "27 Total People, 0 recently added",
    "You have no remaining numbers / Purchase additional numbers for $4/mo; (314) 701-6954 Vmail Answer / (314) 701-6954 Vmail Answer / (816) 731-1363 Completed (call history rows)",
    "Total People 27 (0 recently added); 25 Opted in, 2 Opted out (For SMS Communication); 27 Opted in (For Email Communication)",
    "27 Total People, 0 recently added, 24 SMS Opted in, 27 Email Opted in",
    "July 19, 2024/churchqrco.de row at position 3, December 2, 2025/into.church row at position 1 (URL Shortener rows)",
    "27 Total People, 0 recently added; 24 SMS Opted in; 27 Email Opted in",
    "27 Total People, 0 recently added; 24 SMS Opted in; 27 Email Opted in"};

const int textBeforeLen = 606;