#include <stdio.h>

const char *textAfter[] = {
    "Cancel; Manhattan Beach; Sat, Feb 13, 2027, 6:00 PM UTC; Tue, Feb 16, 2027, 2:00 AM UTC; Thu, Feb 12, 2026, 12:19 PM",
    "Manhattan Beach; Feb 18, 2026",
    "Manhattan Beach",
    "Manhattan Beach — Manhattan Beach, CA, USA",
    "Manhattan Beach; Josh Peacock sent a reply via email from Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach; Team owner: Manhattan Beach / Manhattan Beach, CA, USA; Access row: Manhattan Beach / Manhattan Beach, CA, USA",
    "Manhattan Beach; Available hours set; Manhattan Beach; Manhattan Beach (owner)",
    "Manhattan Beach; Ross Geller / mark lopez / Darrell Ciatti (customer rows re-shuffled, new top row its_zaya1@yahoo.com, Feb 5, 11:55 PM)",
    "Manhattan Beach; Ross Geller / mark lopez / Darrell Ciatti (customer rows re-shuffled, new top row its_zaya1@yahoo.com, Feb 5, 11:55 PM)",
    "Manhattan Beach; Manhattan Beach / Manhattan Beach; Manhattan Beach / zaya@endearhq.com (hosted calendar); Include calendars owned by the all members of Manhattan Beach",
    "Manhattan Beach; Manhattan Beach / Manhattan Beach; Manhattan Beach / zaya@endearhq.com (hosted calendar); Include calendars owned by the all members of Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach; M (pink badge, Owner column, Manhattan Beach rows)",
    "Manhattan Beach; M (pink badge, Owner column, Manhattan Beach rows)",
    "Ross Geller / zaya1@yahoo.com / Feb 5, 2025 (new row inserted at top); Manhattan Beach; Endear Team / hello@endearhq.com / Apr 25, 2025, 12:53 AM",
    "Ross Geller / zaya1@yahoo.com / Feb 5, 2025 (new row inserted at top); Manhattan Beach; Endear Team / hello@endearhq.com / Apr 25, 2025, 12:53 AM",
    "Manhattan Beach; Created by me (1); Subscribed to SMS Marketing",
    "Manhattan Beach; Created by me (1); Subscribed to SMS Marketing",
    "Manhattan Beach; Ross Geller / its_zaya1@yahoo.com / Feb 5, 2025 (new top customer row)",
    "Manhattan Beach; Ross Geller / its_zaya1@yahoo.com / Feb 5, 2025 (new top customer row)",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach; Showing 6 of 6 conversations; Book an Appointment - Hi there, Let us know if you'd like to book a virtual styling or in-store appointment so you can see the pieces in perso... (new top row); Pheebs Buffay / Hello there! - Hi Phoebe, I wanted to let you know we're having a sample sale this weeken... (row shifted down)",
    "Manhattan Beach",
    "Manhattan Beach; Ross Geller / its_zaya1@yahoo.com / Feb 5, 11:55 PM (new top customer row); Endear Team / hello@endearhq.com / Apr 25, 12:53 AM; mark lopez, Duncan Regan, ben@endearhq.com, Josh Greene, Chandler Bing (customer rows reshuffled)",
    "Manhattan Beach; Ross Geller / its_zaya1@yahoo.com / Feb 5, 11:55 PM (new top customer row); Endear Team / hello@endearhq.com / Apr 25, 12:53 AM; mark lopez, Duncan Regan, ben@endearhq.com, Josh Greene, Chandler Bing (customer rows reshuffled)",
    "Team is Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach; Pheebs Buffay",
    "Manhattan Beach; Pheebs Buffay",
    "Team is Manhattan Beach",
    "Team is Manhattan Beach",
    "Manhattan Beach; Ross Geller (new row, Feb 5 2026) / mark lopez / Duncan Regan / ben@endearhq.com / Josh Greene / Chandler Bing (customer rows shifted down), jackson.giannoni@sink.sendgrid.net / darrell.ciatti@sink.sendgrid.net (email rotation shifted); Pheebs Buffay",
    "Manhattan Beach; Ross Geller (new row, Feb 5 2026) / mark lopez / Duncan Regan / ben@endearhq.com / Josh Greene / Chandler Bing (customer rows shifted down), jackson.giannoni@sink.sendgrid.net / darrell.ciatti@sink.sendgrid.net (email rotation shifted); Pheebs Buffay",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach / Manhattan Beach, CA, USA; Away",
    "Manhattan Beach / Manhattan Beach, CA, USA; Away",
    "Manhattan Beach; Pheebs Buffay; last mo",
    "Manhattan Beach; Ross Geller (new top customer row)",
    "Hermosa Beach / Hermosa Beach, CA, USA",
    "M",
    "Manhattan Beach; Showing 15 of 464 conversations; Book an Appointment - Hi [Name], Let us know if you'd like to book a virtual styling or in-store appointment... (Lloyd Vannini, Genevieve Maxwell, Benjamin Collier rows)",
    "387; Manhattan Beach",
    "Manhattan Beach; Manhattan Beach, CA, USA",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach; Ross Geller / its_zaya1@yahoo.com / Feb 5, 2025 (new top customer row, drops Mollie Verheul off bottom)",
    "Pheebs Buffay; Hi Pheebs,",
    "Manhattan Beach",
    "Hermosa Beach / Manhattan Beach (selected) / Redondo Beach; Away",
    "Manhattan Beach",
    "icon-only rail, no text labels; none (search collapsed to icon)",
    "none (icon-only); none (name field cleared); Mini Crossbody Bag (new bag entry, slot 4); Mini Crossbody Bag (new bag entry, different angle, slot 5)",
    "no change",
    "Created by me (1)",
    "Unpin from top",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Manhattan Beach",
    "Today's opportunities / No opportunities available right now. We're analyzing your customer patterns and recent activity. We'll notify you when someone's ready to hear from you. Check back later today, or we'll send a notification when opportunities arrive. / View past conversations; Active; This Week / Messages sent 0 / Attributed sales $0",
    "Today's opportunities; No opportunities available right now. We're analyzing your customer patterns and recent activity. We'll notify you when someone's ready to hear from you. Check back later today, or we'll send a notification when opportunities arrive.; View past conversations (new button); This Week — Messages sent 0, Attributed sales $0",
    "Today's opportunities / No opportunities available right now. We're analyzing your customer patterns and recent activity. We'll notify you when someone's ready to hear from you. Check back later today, or we'll send a notification when opportunities arrive. / View past conversations; Active; This Week / Messages sent 0 / Attributed sales $0",
    "On; Define schedule (Sunday-Saturday day rows with time ranges + timezone); Behavior when outside working hours (Away/Hidden); M icon-only collapsed sidebar",
    "Working hours On; Define schedule — Set the hours and time zone that you are available to chat with customers. Sunday–Saturday rows, 08:00 AM–06:00 PM, America/New_York; Behavior when outside working hours — Set the behavior of the widget when outside of the working hours. Away / Hidden; none (icon-only)",
    "On; Define schedule (Sunday-Saturday day rows with time ranges + timezone); Behavior when outside working hours (Away/Hidden); M icon-only collapsed sidebar",
    "Stories",
    "no change",
    "None",
    "Phoebe Buffay",
    "none (icon-only rail, no text labels or profile name)",
    "none (icon-only rail); none (icon-only)",
    "no change",
    "Phoebe Buffay",
    "none",
    "Falcon Midi Dress (new item added, first slot)",
    "Akta Adani, Jinesh Shah, User Zaya, Monica Geller, Liza Lopez, Zaya Amgaabaatar, Jasmine Tudor, Josh Peacock, Rachel Green (9 unique staff rows); none",
    "no change",
    "no change",
    "no change",
    "Navigation Style - Choose your navigation appearance (Old/New toggle, New selected); PIN-Enabled Devices - Register devices to enable PIN code login for your teams",
    "none",
    "none",
    "none",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "Navigation Style / Choose your navigation appearance / Old / New; Notifications, Billing, Brand, Security, PIN-Enabled Devices, Staff",
    "Navigation Style — Choose your navigation appearance (Old / New); PIN-Enabled Devices — Register devices to enable PIN code login for your teams",
    "Navigation Style / Choose your navigation appearance / Old / New; Notifications, Billing, Brand, Security, PIN-Enabled Devices, Staff",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "none; Navigation Style / Choose your navigation appearance / Old / New; PIN-Enabled Devices / Register devices to enable PIN code login for your teams",
    "no change",
    "no change",
    "My new task",
    "My new task",
    "Active",
    "Active",
    "icon-only rail, no text labels; none (search collapsed to icon)",
    "no change",
    "no change",
    "icon-only dark rail, no text labels; < Campaigns",
    "icon-only rail, no labels; Save (new button in compose toolbar); [redacted/blacked-out search bar]; Phoebe Buffay",
    "Personal Styling Session / During this appointment, we will reserve a private fitting room for you and help you style 2-3 pieces...; Phoebe Buffay; 1 selected / Edit; none",
    "Montserrat",
    "Phoebe Buffay; none",
    "no change",
    "Save",
    "Personal Styling Session; During this appointment, we will reserve a private fitting room for you and help you style 2-3 pieces....; 1 selected; none",
    "no change",
    "no change",
    "Save",
    "Phoebe Buffay",
    "no change",
    "no change",
    "no change",
    "no change",
    "none (icon-only, labels removed)",
    "none (icon-only nav rail, no labels or org banner); none (blank/redacted input); Band Tee, Ribbed Bodycon Midi Dress, Mini Crossbody Bag, second bag (image grid reordered)",
    "none (icon-only rail, no text labels or profile name); Create campaign",
    "no change",
    "no change",
    "My new task",
    "Title, Status, Type, Start date, End date, Schedule, Next run start date, Creator, Date created",
    "no change",
    "none; none; none",
    "none; none",
    "none (collapsed icon-only rail); Notifications, Billing, Brand, Security, PIN-Enabled Devices, Staff; Navigation Style - Choose your navigation appearance (Old / New); PIN-Enabled Devices / Register devices to enable PIN code login for your teams",
    "no change",
    "9mo ago / 6mo ago / 3mo ago",
    "no change",
    "icon-only dark rail, no labels, M avatar only",
    "M > All customers / 462 customers; 11410 Century Oaks Terrace (new Address column)",
    "no change",
    "I like the grey one and the navy one - I'll swing by this weekend to try them on. What time are you guys open?; We're open [days/times].; Save, Schedule, Send email",
    "icon-only dark rail (collapsed sidebar, no text labels); None None (Last activity, for some customer rows); street addresses (Address column, e.g. Chandler Bing, Phoebe Buffay, Glen Vannoni rows)",
    "none (icon-only rail, labels removed); Chandler Bing (new breadcrumb header with back arrow and avatar); Save (new button); 10mo ago / 9mo ago",
    "Save",
    "no change",
    "none",
    "no change",
    "no change",
    "10mo ago; 9mo ago — opened; Save (new button near compose actions)",
    "Create campaign / Add task / Add customer; First Seen (new column with dates); Jasmine Tudor, Jinesh Shah",
    "Redondo Beach",
    "no change",
    "none (icon-only collapsed rail)",
    "bare color-letter avatars, no location text (5 rows)",
    "no change",
    "no change",
    "no change",
    "no change",
    "Baked Design/@bakeddesign, Jasmine Tudor/@jasminetudor (Creator checklist)",
    "Birthday: Mar 14; Address: Tribeca",
    "Page Views 1",
    "Page Views 1",
    "Showing 8 of 8 stories; Untitled Story / 1 Piece (new denim-jeans card)",
    "no change",
    "no change",
    "no change",
    "Blocked; 63 appointments; Try the new calendar view — switch back anytime. (new banner); Jun 27, 2025 / Jun 13, 2025 / Jun 20, 2025 3:00 AM UTC (row dates, many more rows, no pagination footer)",
    "no change",
    "no change",
    "no change",
    "Spencer Whitmore / Penelope Ashby / Lucas Greyson / Florence Kingsley / Matthias Pendleton (customer list rows, with matching emails, phones, dates)",
    "Fri, May 29, 2026, 10:00 AM - 12:00 PM UTC; Fri, Jun 5, 2026 ... Jun 26, 2026 (remaining rows); Fri, Jul 3, 2026, 10:00 AM - 12:00 PM UTC",
    "no change",
    "no change",
    "Try the new calendar view — switch back anytime.",
    "May 18, 2026 — Zaya Amgaabaatar left a note 9:29 PM; In-store visit with Chandler Bing / Chandler came in today looking for work clothes - wears a 32x32 in pants, likes navy, black, and grey / in-store",
    "no change",
    "AI Opportunity Engine – Help your team send more personalized messages in less time. AI identifies high-intent customers and drafts messages for associate review.; none; Configure for your brand (new button); Phoebe Buffay / Fri, May 29, 2026, 5:45 PM UTC - Event Styling; SMS reply to Phoebe Buffay / Email to Phoebe Buffay",
    "2 total issues must be resolved before scheduling; 2. A signature block is required for email campaigns. Review these 2 variations: Redondo Beach / HQ",
    "1",
    "May 24, 2026",
    "no change",
    "Showing 15 of 16 templates; Post-purchase follow-u... / Hi {{customer.first_name|there}}, thanks for shopping with example brand... (new template rows)",
    "None",
    "None",
    "no change",
    "no change",
    "no change",
    "no change",
    "Pant size: width (new field, dated May 18 2026, description Men's pant size: width); Pant size: length / Men's pant size: length; Preferred Fabrics / These are the fabrics the customer shares as their preferred ones., Loyalty Status / Customer's loyalty status, Color Palette / What colors does this person enjoy wearing?",
    "Birthday: Mar 14, Address: Tribeca (Phoebe Buffay row)",
    "Birthday: Mar 14, Address: Tribeca (Phoebe Buffay row)",
    "no change",
    "no change",
    "Showing 8 of 8 stories; Copy of My Story",
    "Showing 8 of 8 stories; Copy of My Story",
    "no change",
    "no change",
    "Showing 10 of 10 stories; Picks for Chandler; Summer Linen Faves (new untitled/blank story card)",
    "Showing 10 of 10 stories; Picks for Chandler; Summer Linen Faves (new untitled/blank story card)",
    "Page Views 1",
    "Page Views 1",
    "Page Views 1",
    "Page Views 1",
    "no change",
    "no change",
    "no change",
    "no change",
    "Showing 10 of 10 stories; Picks for Chandler (3 Pieces); Summer Faves - Shoppable (6 Pieces); Untitled Story / Summer Linen Faves (new empty placeholder cards)",
    "Showing 10 of 10 stories; Picks for Chandler (3 Pieces); Summer Faves - Shoppable (6 Pieces); Untitled Story / Summer Linen Faves (new empty placeholder cards)",
    "no change",
    "no change",
    "The 13th, 17th, 19th, 22nd of Jun; May 31st from 10am - 12pm",
    "The 13th, 17th, 19th, 22nd of Jun; May 31st from 10am - 12pm",
    "3 selected; Redondo Beach (Hosted)",
    "3 selected; Redondo Beach (Hosted)",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "90 appointments; Rescheduled, Rescheduled by Zaya Amgaabaatar (new status on top row); Zaya Amgaabaatar, Monica Geller, Rachel Green (Assigned to column, staff names)",
    "no change",
    "Jasmine Tudor @jasminetudor; All users, managers, and admins; Hermosa Beach, John Jackson (member list swap)",
    "Showing 11 of 11 conversations; New Open section with Duncan Regan - Re: Test - Thanks!; Joey Tribbiani, Bertie Carlesi, Ross Geller, Chandler Bing (new closed-conversation rows)",
    "no change",
    "Josh Peacock contact card + Manhattan Beach location card (Staff/Settings tabs); AI Opportunity Engine panel - Help your team send more personalized messages in less time. Configure for your brand; Quick actions grid (Setup guide, Send a message, Add a customer, Leave a note, Create a task, Book an appointment, Log a purchase, My inbox, My customers); Phoebe Buffay - Fri, May 29 2026, 5:45 PM UTC - Event Styling; Any tasks assigned to you will appear here (empty placeholder); SMS reply to Phoebe Buffay, Email to Phoebe Buffay - Hi {{customer.first_name|there}}",
    "Josh Peacock @joshpeacock / Manhattan Beach, CA, USA (bound customer card); AI Opportunity Engine - Help your team send more personalized messages in less time. Learn more / Configure for your brand; Quick actions - Setup guide, Send a message, Add a customer, Leave a note, Create a task, Book an appointment; Phoebe Buffay - Fri, May 29, 2026, 5:45 PM UTC - Event Styling; SMS reply to Phoebe Buffay / Email to Phoebe Buffay",
    "no change",
    "no change",
    "Phoebe Buffay: Birthday Mar 14; Phoebe Buffay: Address Tribeca",
    "no change",
    "Selected 47 contacts; Andrea / ajmorrison1993@gmail.com / L Reiff / kamille aerron / kamilleaerrondeguzman@gmail.com (new rows inserted at top); Nov 21, 2025",
    "no change",
    "no change",
    "no change",
    "KAJABI / $612/mo",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "About; www.thrivefitcollective.com/about; Views All Time: 33; Theme: Taylor; Created: Feb 26 2026 7:57PM, Updated: Mar 2 2026 7:52PM; chart dates 2026-05-02 to 2026-05-09",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "EDIT",
    "no change",
    "no change",
    "You've already built the 30-Day Transformation Challenge offer.",
    "You've already built the 30-Day Transformation Challenge offer.",
    "You've already built the 30-Day Transformation Challenge offer.",
    "no change",
    "You've already built the 30-Day Transformation Challenge offer.",
    "You've already built the 30-Day Transformation Challenge offer.",
    "You've already built the 30-Day Transformation Challenge offer.",
    "You've already built the 30-Day Transformation Challenge offer.",
    "www.thrivefitcollective.com/affiliate_users/sign_up; ThriveFit Collective Affiliates (sign-up page heading); Join now!; Healthy Living - Fitness Recommendations for Adults & Kids (Resources entry added); Require PayPal email address at sign-up: checked; You've already built the 30-Day Transformation Challenge offer (toast/tooltip)",
    "no change",
    "no change",
    "You've already built the 30-Day Transformation Challenge offer.; Backstage",
    "You've already built the 30-Day Transformation Challenge offer.",
    "You've already built the 30-Day Transformation Challenge offer.",
    "no change",
    "no change",
    "no change",
    "no change",
    "Backstage; You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer; Backstage",
    "Backstage; You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer; Backstage",
    "no change",
    "Backstage; You've already built the 30-Day Transformation Challenge offer.",
    "You've already built the 30-Day Transformation Challenge offer; Backstage (new sidebar nav item)",
    "Backstage; You've already built the 30-Day Transformation Challenge offer",
    "Backstage; You've already built the 30-Day Transformation Challenge offer; 9 (selected calendar day)",
    "Backstage; You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer; Backstage",
    "no change",
    "no change",
    "no change",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "no change",
    "Backstage",
    "Backstage",
    "Backstage",
    "Energize Your Life: Top Tips for Maintaining Consistent Home Fitness Routines; Hello fitness enthusiasts! Welcome to this week's edition of our newsletter. We're excited to share some top tips to help you maintain consistent home fitness routines and energize your life. Let's dive in and discover how to keep the fitness flame burning, even when life gets busy.; Creating a Routine; Consistency is key in fitness, and having a routine can make all the difference. Start by setting specific workout days and times. Make it a non-negotiable appointment with yourself. Remember, it's not about having time, it's about making time. What's your favorite time to workout? Share your thoughts and let's inspire each other!",
    "no change",
    "Thank You Page (dropdown, appears when custom thank you page checkbox is checked); Choose which Landing Page to take the user to after they fill out this form; Pass submission data to the thank you page (enabled toggle); Backstage",
    "Welcome to ThriveFit's Pre-sale List for Complete Digital Marketing Mastery!; Dear ThriveFit Family, Thank you for joining the pre-sale list for our upcoming online course, Complete Digital Marketing Mastery for Small Business Owners, From Zero to $10K Monthly Revenue... (Exclusive Updates / Priority Access bullet list); Join waitlist; Automation Masterclass Presale Landin...",
    "Automation Masterclass Presale Landin... (Landing page selector); Automations help you set up repeating tasks and streamline your workflow with just a few clicks. (empty state)",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "no change",
    "Get your free nutrition guide instantly when you register today!; Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "Backstage",
    "no change",
    "no change",
    "Backstage",
    "Backstage",
    "no change",
    "no change",
    "no change",
    "Backstage",
    "Backstage",
    "no change",
    "Backstage",
    "You've already built the 30-Day Transformation Challenge offer; Active Users 28; Last updated: May 09 2026, 05:54 PM UTC; Backstage (new sidebar nav item); Messages sent 7 more; Apr 9",
    "no change",
    "no change",
    "Josh Peacock (photo-banner panel, no email shown); Sessions / Clients (0) / Offers (0) / Settings (tab bar); Group Coaching / Session 1 May 19 2026, Sessions 2-4, Ad hoc session; You've already built the 30-Day Transformation Challenge offer (tooltip)",
    "Backstage; You've already built the 30-Day Transformation Challenge offer",
    "Backstage; You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer",
    "Completed text / You've completed this assessment.; none",
    "no change",
    "ThriveFit; You've already built the 30-Day Transformation Challenge offer; Backstage",
    "Backstage; You've already built the 30-Day Transformation Challenge offer",
    "Josh Peacock; You've already built the 30-Day Transformation Challenge offer (tooltip); Displaying 1-8 of 8 contacts; Kay Halsey / Josh Peacock / Vernon Hays / Marcus Grant / Janee Halst / Didi Golin / Gen Hall (mostly Never subscribed)",
    "Integrations & Webhooks; Backstage (new sidebar nav item); You've already built the 30-Day Transformation Challenge offer (new tooltip); Josh Peacock",
    "Apr 24 - May 1 / May 2 - May 9",
    "The Beginner's Guide to Strength Training: Your First Step to a Stronger You (Apr 24, 2026); Showing 1-1 of 1 results; Josh Peacock; You've already built the 30-Day Transformation Challenge offer; Backstage",
    "You've already built the 30-Day Transformation Challenge offer",
    "You've already built the 30-Day Transformation Challenge offer",
    "Summary $0.00 Sales / 0 Offers Sold / 0 First Purchases; No data yet; You've already built the 30-Day Transformation Challenge offer (tooltip)",
    "OFFERS SOLD 0; Summary $0.00 / 0 offers sold / 0 first purchases; none",
    "no change",
    "Newsletter Subscribe/Newsletter Post/Newsletter/Member Directory/Login/Library/Contact (Updated February 26, 2026 07:57 PM, STRONG BODY BOLD LIFE thumbnails), Josh Peacock; You've already built the 30-Day Transformation Challenge offer.",
    "no change",
    "Backstage (new sidebar item); You've already built the 30-Day Transformation Challenge offer; Josh Peacock",
    "Ready to Transform? Unlock Your Fitness Journey Today!; Feel stronger, healthier, and more energized-all from the comfort of your...; Josh Peacock; You've already built the 30-Day Transformation Challenge offer.",
    "Photography Basics",
    "Revenue recovered from abandoned checkout emails / Displays recovery metrics for abandoned checkout email campaigns over time, tracking sent, opened, clicked, and recovered checkout emails.; Upsell Purchases Over Time / Upsell purchases, revenue, and conversion metrics; Josh Peacock; Analytics > Overview, Reports; You've already built the 30-Day Transformation Challenge offer",
    "Fuel Your Fitness - The Ultima... / Stronger Every Day - The Ess... / 2 Downloads; Josh Peacock",
    "Displaying 1 Funnels: Fitness Freebie Funnel; You've already built the 30-Day Transformation Challenge offer; Josh Peacock",
    "Displaying 16 Website Pages; About / Home / Thank You / Store (Published badge on first row); Josh Peacock; You've already built the 30-Day Transformation Challenge offer (tooltip)",
    "You've already built the 30-Day Transformation Challenge offer",
    "Josh Peacock; You've already built the 30-Day Transformation Challenge offer (tooltip); Contacts, Backstage (new nav items); 3 Events; Group Coaching (Session 2-4 rows)",
    "no change",
    "Backstage; You've already built the 30-Day Transformation Challenge offer; Complete Digital Marketing Mastery for Small Business Owners: From Zero to $10K Monthly Revenue Waitlist / Freebie Funnel Form / ddd - Cohort 1 Waitlist (forms rows); none; none",
    "ThriveFit; ThriveFit Collective; Connect, support, and grow with fellow fitness enthusiasts in the ThriveFit Collective—a positive community focused on health, motivation, and reaching your goals together.; You've already built the 30-Day Transformation Challenge offer",
    "ThriveFit / ThriveFit Collective; Connect, support, and grow with fellow fitness enthusiasts in the ThriveFit Collective, a positive community focused on health, motivation, and reaching your goals together.; none",
    "no change",
    "Squiggle, Slice, Timber, Learn Guitar, Your Next Painting Adventure Starts Today!, Welcome (photo-rich template cards); You've already built the 30-Day Transformation Challenge offer (tooltip)",
    "Backstage; Josh Peacock; You've already built the 30-Day Transformation Challenge offer (coach-mark tooltip); Try adjusting your filters to find what you're looking for. (empty state); Value... (filter chip placeholder)",
    "no change",
    "no change",
    "no change",
    "no change",
    "Redirect contacts to custom confirmation page (toggle, with description and Default Confirmation Page link); Freebie Funnel Form; Agents",
    "no change",
    "no change",
    "no change",
    "no change",
    "Agents",
    "no change",
    "Blog - Updated: May 14, 2026 07:56 PM (System); Agents",
    "Agents",
    "Blog / Updated: May 14, 2026 07:56 PM; Displaying 16 Website Pages; Agents",
    "no change",
    "no change",
    "Test options (Updated May 14, 2026 07:20 PM), Fitness Sales Page Funnel Email Sequence (multiple, Active), TEST Email Sequence, Fitness Sales Page Funnel! Email Sequence, Fitness Sales Page Funnel TEST TEST Email Sequence (campaign rows, statuses now mostly Active)",
    "Agents",
    "VIP 1:1; Total Body Strength Program Waitlist; Manage tags; Agents",
    "VIP 1:1, Total Body Strength Program Waitlist, Manage tags; Agents",
    "Blog (first, Updated May 14, 2026)",
    "Updated 6 days ago; Agents; Update",
    "Agents",
    "Agents",
    "Agents",
    "Agents",
    "Agents",
    "no change",
    "no change",
    "no change",
    "ThriveFit / Settings / Site Details; Agents; You've already built a full 30-Day Transformation Challenge funnel",
    "Agents; You've already built a full 30-Day Transformation Challenge funnel",
    "Agents",
    "You've already built a full 30-Day Transformation Challenge funnel",
    "Offers (1)",
    "You've already built a full 30-Day Transformation Challenge funnel; Clients (1); Offers (1); Agents; Contacts",
    "You've already built a full 30-Day Transformation Challenge funnel",
    "You've already built a full 30-Day Transformation Challenge funnel",
    "You've already built a full 30-Day Transformation Challenge funnel",
    "Raja Johnson - VIP 1:1 Coaching (session card, Jun 24, 2026 at 4:30 PM, Session 1); Enrolled clients 1; 2 Events; Agents; You've already built a full 30-Day Transformation Challenge funnel",
    "You've already built a full 30-Day Transformation Challenge funnel",
    "Amplify; none",
    "none; Amplify (nav item)",
    "4 images found on this page not yet in your Media Library. Import them to reuse across your site. Import all; none",
    "Amplify (new sidebar nav item); none",
    "Amplify; none",
    "Amplify; none",
    "Amplify; none",
    "Amplify; none",
    "Amplify; none",
    "Corey Piazza (LB) Export of Recent Incoming Messages — Sent on: December 9, 2025 10:19 AM; Message details Sent: December 9, 2025 10:19 AM",
    "Corey Piazza (LB) — Export of Recent Incoming Messages — Sent on: December 9, 2025 10:19 AM (new top entry, existing rows shift down unchanged)",
    "Filters: All, Email, SMS, Voice Broadcast, Reminder; Corey Piazza (LB) / Export of Recent Incoming Messages / Sent on: August 14, 2025 1:24 PM (message rows)",
    "Corey Piazza (LB) Export of Recent Incoming Messages — Sent on: December 9, 2025 10:19 AM",
    "(304) 807-4477 / (304) 807-4478; Connect Cards (7)",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "[Recovering] Application Slowness Updated 31 Jan 23:47 - Click for details; Upgrade to a larger plan / Crafting the perfect text message / Using Groups / Keywords",
    "no change",
    "no change",
    "no change",
    "(816) 813-6725, SMS Created 2026-01-12 06:59:54 AM, Sent on: January 12, 2026 6:59 AM (new entry at top)",
    "no change",
    "no change",
    "no change",
    "no change",
    "Settings > Referral",
    "no change",
    "no change",
    "no change",
    "no change",
    "Messages; People",
    "(816) 81..., (913) 30..., (816) 457-3252 (3 phone contacts above Daniel Murphy, new contact added)",
    "no change",
    "no change",
    "info icon next to Search box",
    "no change",
    "People Created 0, Out of 23 total; Emails Sent 0; People donut 24, 3 Incoming Message",
    "192 days ago",
    "no change",
    "no change",
    "Caller ID (column header)",
    "no change",
    "no change",
    "no change",
    "Prayer Request Playbook™ - Reach; Workflow Trigger - Calendar Date; Send \"How can I pray for you?\" On 11/14/2025 / Send \"Share joys or struggles\" 187 days After / Send \"God of hope encouragement\" 219 days After (new first step inserted, list shifted)",
    "Ask Your Questions",
    "no change",
    "Groups | People | Reports",
    "no change",
    "no change",
    "Hi, thanks for calling . If you know your party's extension, you may dial it anytime. Please listen carefully as our menu options have changed. To hear our service times and locations, press 1. If you're new and would like to plan your visit, press 2. To share a prayer request with our prayer team, press 3. If you'd like to learn about service opportunities, press 4. For our staff directory press",
    "no change",
    "5 People Created (Out of 27 total); 10 Calling (3 Completed, 16 Incoming Call); 28 People (6 Incoming Call); 1.82 Minutes Used",
    "3 Completed; 16 Incoming Call",
    "1.82 Minutes Used, 5 People Created (Out of 27 total); 10 calls, 3 Completed; 28 People, 16 Incoming Call",
    "5 People Created; Out of 27 total; 10 Calling (6 Incoming Call, 2 Voicemails, 3 Completed); 28 People; 1.82 Minutes Used",
    "People Created 5 (Out of 27 total); Calling 10; People 28; Minutes Used 1.82",
    "We will not share your contact info. By clicking submit you agree to receive communications from Test Account for Apps - DO NOT DELETE OR CHANGE (frequency varies). Message and data rates may apply. Text STOP at any time to cancel or text HELP for help. Privacy Policy & Terms of Use apply.",
    "5 People Created, Out of 27 total; 1.82 Minutes Used; Calling: 10 total, 3 Completed; People: 28 total",
    "no change",
    "no change",
    "no change",
    "0.00 Minutes Used; People Created 0 of 27 total; Calling 0 (0 Completed, 0 Outgoing, 0 Voicemails, 0 Missed); People 28 (16 Incoming Call)",
    "We will not share your contact info. By clicking submit you agree to receive communications from Test Account for Apps - DO NOT DELETE OR CHANGE (frequency varies). Message and data rates may apply. Text STOP at any time to cancel or text HELP for help. Privacy Policy & Terms of Use apply.; Powered by Text In Church",
    "Hi {FIRST_NAME}...",
    "no change",
    "no change",
    "no change",
    "You have 1 free number remaining.; (816) 731-1362",
    "You have 1 free number remaining.; 60 Receptionist",
    "10-23-2025 / 01-23-2026 / 2-23-2026 (invoice date rows, top row)",
    "From: Emily <emily@test.com>",
    "27 Total People; 0 recently added; 25 Opted in / SMS Communication; 27 Opted in / Email Communication",
    "Connect Cards (4)",
    "27 Total People; 25 Opted in (SMS); 27 Opted in (Email); 0 recently added",
    "Enter value (not set); Enter value (not set); Enter value (not set)",
    "Visible invoice dates: 10-23-2025 through 05-23-2025 (7 rows)",
    "Thanks for your interest in Thrive. Please check your text messages for a message from us.; Thanks for reaching out! Here's the link to our website: https://textinchurch.com Let us know if you have any questions! (120/160 chars)",
    "3 Phone Number",
    "Hi {FIRST_NAME} - it's {PASTOR_FNAME} here...we hope to see you tomorrow @ {CHURCH_NAME}!",
    "Hi {FIRST_NAME}...",
    "27 Total People; 25 SMS Opted In; 27 Email Opted In; 0 recently added",
    "27 (Total People); 0 recently added",
    "27 (Total People); 25 (Opted in, SMS Communication); 27 (Opted in, Email Communication); 0 recently added",
    "no change",
    "no change",
    "no change",
    "no change",
    "no change",
    "27 Total People; 3 Opted out (SMS); 27 Opted in (Email)",
    "27 Total People; 24 Opted in / 3 Opted out SMS; 27 / 0 Email",
    "no change",
    "Blocked (top-level tab: User Created | System Created | Blocked | Archived); Total People 27, SMS opted in/out 24/3, Email opted in/out 27/0",
    "Out of 28 total; 2.57 Minutes Used; 13 calls, 4 Completed, 5 Outgoing",
    "4 Completed, 5 Outgoing, 2 Voicemails, 2 Missed",
    "2.57 Minutes Used; 13 (Calling total); Out of 28 total (People Created); 4 Completed, 5 Outgoing",
    "opened; 1 Opened",
    "Out of 28 total (People Created); 2.57 Minutes Used; 13 calls (Calling donut total); 4 Completed, 5 Outgoing",
    "2.57 Minutes Used; 13 calls; Out of 28 total; 4 Completed; 5 Outgoing",
    "2.57 Minutes Used; Calling 13 (Completed 4, Outgoing 5); Out of 28 total",
    "Keywords; Leadership (sample) Members: 2",
    "Connect Cards (86)",
    "no change",
    "no change",
    "Google Test / Completed / (863) 209-4010; Google Test / Completed / (863) 209-4010",
    "Simulate Workflow; View Report",
    "Google Test Completed, Google Test Completed, Google Test Completed (Call History rows); 87 Receptionist",
    "no change",
    "10-23-2025 / 01-23-2026 / 02-23-2026 (invoice date rows)",
    "Simulate Workflow; View Report",
    "no change",
    "24 Opted in, 3 Opted out (For SMS Communication)",
    "Connect Cards (86)",
    "none",
    "Set up your Digital Receptionist today / Set automated messages for your phone line so callers can easily find the information they are looking for.; Google Test Completed (863) 209-4010 (demo call history rows)",
    "Simulate Workflow; View Report",
    "Keywords",
    "Opted In: 24, Opted Out: 3",
    "Keywords; Leadership (sample): 2 members, 3 workflows",
    "Keywords; Leadership (sample) Members: 2",
    "Connect Cards (86)",
    "no change",
    "none",
    "Keywords (column header); Leadership (sample): 2 members",
    "Simulate Workflow; View Report; Deactivated by Corey Piazza (LB) on August 23rd",
    "Start time: 07:00 PM; End time: 07:00 PM",
    "Deactivated by Corey Piazza (LB) on August 23rd; Simulate Workflow; View Report",
    "10-23-2025 / 11-23-2025 / 12-23-2025 (invoice dates)",
    "All Settings, My Settings (Profile, Call Routing), Account (Users, Notifications, Branding, Tags), Sender Profile, Refer a Friend, Billing, System (grouped nav); Subscription Summary — Review your current plan details, including usage limits and available features.; Subscription Totals: Unlimited Emails per month, Unlimited Contacts, 550 Text Messages per month, 3 Phone Number, 1 Caller; Go Annual Get Two Months Free — Save Ministry Dollars, Convenient Billing, BONUS: 1 extra phone line, Go Annual & Save $NaN per year, Yes, Supercharge My Account",
    "Counters reset on 23rd of every month.",
    "none",
    "Simulate Workflow; View Report",
    "(816) 307-4282, 08-20-2024 4:47 AM, Completed (new row)",
    "no change",
    "Simulate Workflow, View Report (new toolbar buttons)",
    "no change",
    "no change",
    "24 Opted in, 3 Opted out (For SMS Communication)",
    "24 Opted in, 3 Opted out (For SMS Communication)",
    "no change",
    "https://into.church/wuNzTmZ0 (row 1), https://into.church/1WvFa0AE (row 2)",
    "Keywords; First time guest / Leadership (sample) Members: 2 / 2",
    "no change",
    "Google Test (863) 209-4010 Completed x2 / (816) 731-1363 Completed (call history rows)",
    "https://into.church/wuNzTmZ0 (row 1), https://into.church/1WvFa0AE (row 2)",
    "Connect Cards (86)",
    "Keywords; Leadership (sample) Members: 2",
    "24 Opted in, 3 Opted out (For SMS Communication)",
    "Connect Cards (86)",
    "Keywords; 2 (Leadership (sample) row, Members column)",
    "24 Opted in, 3 Opted out (For SMS Communication)",
    "Connect Cards (86)",
    "Google Test Completed x2, (816) 731-1363 Completed",
    "no change",
    "Google Test (863) 209-4010 Completed; Google Test (863) 209-4010 Completed; (816) 731-1363 Completed",
    "24 Opted in, 3 Opted out (For SMS Communication)",
    "Corey Piazza (LB) only, rest blank (list rows)",
    "28 Total People; 1 recently added; 25 Opted in SMS; 28 Opted in Email",
    "Top rows: ka3vZb5, 55EpvPwd, wuNzTmZ0, 1WvFa0AE, fMuJo4vw, SeE90vRI (destination-URL codes)",
    "(816) 752-4453 / No Answer, (816) 731-1362 / Completed, (816) 731-1352 / Completed",
    "People Created Out of 29 total; 17 In (Calling badge)",
    "276 days ago; Jul 24",
    "(816) 752-4453, No Answer (row 1); (816) 731-1362, Completed (row 2); (816) 731-1352, Completed (row 3, new)",
    "29 (People donut center); Out of 29 total (People Created); 17 Incoming Call",
    "Test Account Number / (816) 750-5834 (top rows: (816) 752-4453 Apr 22 2026 no-answer, (816) 731-1362 Apr 6 2026, (816) 731-1352 Mar 30 2026)",
    "28 Total People, 1 recently added",
    "You have 1 free number remaining; (816) 752-4453 No Answer / (816) 731-1362 Completed / (816) 731-1352 Completed (call history rows)",
    "Total People 28 (1 recently added); 24 Opted in, 3 Opted out (For SMS Communication); 28 Opted in (For Email Communication)",
    "28 Total People, 1 recently added, 25 SMS Opted in, 28 Email Opted in",
    "July 19, 2024/churchqrco.de row moved to position 1, December 2, 2025/into.church row moved to position 3 (URL Shortener rows)",
    "28 Total People, 1 recently added; 25 SMS Opted in; 28 Email Opted in",
    "28 Total People, 1 recently added; 25 SMS Opted in; 28 Email Opted in"};

const int textAfterLen = 606;